### ISSUE TITLE
spike-in normalization of bigwigs fails miserably

### ISSUE THREAD

**Issue by snystrom** [snystrom/cutNrun-pipeline#44]
Found by Alex.

Things to fix:

- add `samtoolsVer` to envmodules loading command
- get fixed rule from Alex

**Comment by half-adder** [comment]
Is this still a problem?

**Comment by snystrom** [comment]
Alex found a fix but I never got the patch, and it's not merged on McKaylab either, so I assume so.

**Comment by snystrom** [comment]
there's a thread on the slack somewhere about it, too if you can find it.

**Comment by snystrom** [comment]
By the way if you do get the fix, please send a PR or just shoot me the .patch file, I'd love to know the issue.

**Comment by half-adder** [comment]
Is this the thread?
https://mckaylabunc.slack.com/archives/CSXV0JLFP/p1625601293097400

**Comment by snystrom** [comment]
Ah whoops never replied here. I am not sure if that's the thread, I am not on the Slack anymore.

**Comment by mniederhuber** [comment]
I think I found the error that caused the spike normalization to fail. 

in `rule makeSpikeNormFragmentBedGraphs` there is an errant forward slash that I believe escapes the end quote. The `spikeScale` variable is not assigned any value. Removing that backslash seems to fix things, but I haven't tested with more than one spike-in genome.

**Comment by snystrom** [comment]
Oh my god. Thank you. I think about this issue multiple times a month.
